### ISSUE TITLE
Please add config options

### ISSUE THREAD

**Issue by Some-Doofus** [AstralOrdana/Immersive-Weathering-Fabric#10]
I love the idea of this mod but I feel it can be too intrusive without the ability to config which effects are active and how long each type of weathering takes. I'd love the option to make weathering take longer to occur, especially for cobblestone growing moss near water. Structures near water have a significant cover of moss within a single in game day which isn't very realistic imo. It would be great if the config was integrated with Mod Menu as well to more easily fine tune weathering rates.

**Comment by AstralOrdana** [comment]
config options for all features of the mod have been planned for a long time but we needed to put out this update with improved performance before we could focus on that.
