### ISSUE TITLE
Suggestion: Add leaf pile generation into tree feature instead of adding a new feature

### ISSUE THREAD

**Issue by legosteenjaap** [AstralOrdana/Immersive-Weathering-Fabric#12]
Otherwise azelea trees won't have azelea leaf piles on worldgen and there wouldn't be leaf piles above trees (for example villager houses).

**Comment by AstralOrdana** [comment]
The current leaf pile system is working as intended.

**Comment by legosteenjaap** [comment]
![2022-03-21_14 48 48](https://user-images.githubusercontent.com/50271899/159275086-4f6225ec-c809-4072-ac72-06b1029c3efd.png)
![2022-03-21_14 49 43](https://user-images.githubusercontent.com/50271899/159275100-b31db941-2ef7-404d-addc-02ef432c2532.png)
These trees don't have leaf piles under them on worldgen.
![2022-03-21_14 53 35](https://user-images.githubusercontent.com/50271899/159275715-90366076-bc64-4f4d-9e51-a4829c4d9d51.png)
These leaves generated on a place where they should not have generated.

Wouldn't it be better if these leaf piles where generated together with trees instead of being a seperate feature?

**Comment by AstralOrdana** [comment]
Again, this is still working as intended. You can't just modify the base tree feature like that even if I wanted to. The leaf piles form below trees over time, there are also leaf piles that generate on forest floors to add some variety.
