### ISSUE TITLE
some bugs and issues with iw (forge) version 1.0.2

### ISSUE THREAD

**Issue by LeonKappaX** [AstralOrdana/Immersive-Weathering-Fabric#14]
- hanging roots don't have a texture if you put them on the side of any block
- deepslate tiles don't use the deepslate tile item to repair, instead, they use the deepslate brick item
this goes for all the tile variants
- the normal nether bricks can't be repaired using the nether brick item
using the nether brick on the wall, slab and or stairs works fine tho
- the normal stone brick block can't be repaired using the stone brick item
using the stone brick on the wall, slab and or stairs works fine tho
- using bone meal on a moss block next to a stone block won't turn the stone block into it's mossy variant
it turns into a moss block instead
- cobblestone wont turn into mossy cobblestone if the method from above is used
- using bone meal on a mossy stone won't turn the normal stone next to it to it's mossy variant
- using the moss clump on stone won't turn it mossy
- right click on a prismarine wall with a pickaxe turns it into a brick wall
- right click on a nether brick wall with a pickaxe gives the player normal bricks
- the "Monch" advancement isn't colored 

I also got this crash report
[logcopyiwforge.txt](https://github.com/AstralOrdana/Immersive-Weathering-Fabric/files/8312392/logcopyiwforge.txt)

**Comment by AstralOrdana** [comment]
Related to: 
"using bone meal on a moss block next to a stone block won't turn the stone block into it's mossy variant
it turns into a moss block instead" and "cobblestone wont turn into mossy cobblestone if the method from above is used"
Those are vanilla behaviors and we do not intend to change those.

Note for the future: please make separate issues for separate bugs, that way we can keep track of what has actually been fixed and what's working as intended.

**Comment by AstralOrdana** [comment]
Closed because bugs have been split up into different issues
