### ISSUE TITLE
Cracking a block via pickaxe wastes durability when used on mossy stone brick and brick blocks

### ISSUE THREAD

**Issue by keyb0unce** [AstralOrdana/Immersive-Weathering-Fabric#3]
When trying to use a pickaxe to crack a mossy stone brick block or mossy brick block, it uses durability but nothing changes on the block (nor do any items appear)

![image](https://user-images.githubusercontent.com/81661263/153739097-41d7e52b-1dd9-4b0e-a5bf-5db157cee6a8.png)

**Comment by keyb0unce** [comment]
(should probably crack the block or the player shouldn't be able to use the pick on them)

**Comment by AstralOrdana** [comment]
fixed
