### ISSUE TITLE
Bad Performance Impact

### ISSUE THREAD

**Issue by AshrielV** [AstralOrdana/Immersive-Weathering-Fabric#4]
I recently uploaded this mod onto a server (~3 players)
I'm playing on Fabric on minecraft 1.18.1. 
As the title states, the server was massively impacted by this mod- on normal tickspeed. Any ideas as to why/how to better optimize the mod for my server? It's an excellent mod.

**Comment by AstralOrdana** [comment]
Could you please state which version of the mod you are playing with and if there are any messages in your log you think might pertain to this?

**Comment by AshrielV** [comment]
I was using the 2.1.1 version of the mod. I will attempt to replicate the lag and take a look at the log

**Comment by AstralOrdana** [comment]
IW is receiving a major rewrite of its code, expect a major performance improvement in the next version
