### ISSUE TITLE
fails to load on world creation screen

### ISSUE THREAD

**Issue by TheRanker** [AstralOrdana/Immersive-Weathering-Fabric#8]
https://crashy.net/JZAUdICHebX9OC4CBahU
https://pastebin.ubuntu.com/p/XfNyyymgNY/
Fabric 0.13.13
minecraft 1.18.2
fabric api 0.48.0

immersive weathering : 2.3.0

fails to create a world.

**Comment by AstralOrdana** [comment]
We are looking into the cause for the incompatibility but for now, you should be able to play fine with either BYG or IW

**Comment by TheRanker** [comment]
thing is.. im a modpack developer... if immersive weathering dont work with byg.. then weathering gets cut and not used. 

also.. please please please implement as config to disable/enable each indiviual feature.

**Comment by TheRanker** [comment]
ive tested byg. IW, and terralith on a test profile... it all works as intended.. unsure what is causing the imcompatiblity.

**Comment by AstralOrdana** [comment]
A config is planned for the future, there's only so much i can do at one time. We are working on figuring out the source of the incompatibility but the purpur stone stairs from byg are causing a conflict and we don't know why.

**Comment by TheRanker** [comment]
understandable.  i can load IW , Terralith, BYG, Terrablender.. with fabric and it all works..  but in my modpack of 300.. i get the purpur errors.  if i find any other info to help , ill provide it here.

**Comment by AstralOrdana** [comment]
we've determined a potential fix on our end and will be pushing a patch shortly

**Comment by TheRanker** [comment]
ill just remove immersive weathering. i aint got time to resolve ur issues.
if i find more indication of whats causing it, ill report it .

otherwise,, mod is removed, and ill continue with my modpacks.

**Comment by AstralOrdana** [comment]
parasite
